C:\Users\Canela Santa\Caixa\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Caixa\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "Base_s.py", line 218, in reopen
TypeError: closer() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "Base_s.py", line 218, in reopen
TypeError: closer() takes exactly 1 argument (2 given)
C:\Users\Canela Santa\Caixa\V1.4.5\Base.exe:2789: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 4504, in cont
  File "Base_s.py", line 1127, in end_sell
  File "Base_s.py", line 902, in clean
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 4504, in cont
  File "Base_s.py", line 1127, in end_sell
  File "Base_s.py", line 902, in clean
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 4504, in cont
  File "Base_s.py", line 1130, in end_sell
  File "Base_s.py", line 4581, in __init__
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 4507, in cont
  File "Base_s.py", line 2493, in end
  File "Base_s.py", line 4581, in __init__
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 4507, in cont
  File "Base_s.py", line 2493, in end
  File "Base_s.py", line 4581, in __init__
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 2869, in pre_run
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 4525, in cont
  File "Base_s.py", line 2783, in remover
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 4504, in cont
  File "Base_s.py", line 1130, in end_sell
  File "Base_s.py", line 4581, in __init__
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 4504, in cont
  File "Base_s.py", line 1130, in end_sell
  File "Base_s.py", line 4581, in __init__
  File "Base_s.py", line 2995, in run
  File "Base_s.py", line 3045, in saver
ValueError: could not convert string to float: 
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 3793, in spreport
  File "Base_s.py", line 4066, in __init__
  File "Base_s.py", line 4092, in __init__
  File "Base_s.py", line 4142, in filler
  File "shelve.pyc", line 121, in __getitem__
  File "bsddb\__init__.pyc", line 270, in __getitem__
  File "bsddb\dbutils.pyc", line 68, in DeadlockWrap
  File "bsddb\__init__.pyc", line 270, in <lambda>
KeyError: 'winning'
Traceback (most recent call last):
  File "Base_s.py", line 3793, in spreport
  File "Base_s.py", line 4066, in __init__
  File "Base_s.py", line 4092, in __init__
  File "Base_s.py", line 4142, in filler
  File "shelve.pyc", line 121, in __getitem__
  File "bsddb\__init__.pyc", line 270, in __getitem__
  File "bsddb\dbutils.pyc", line 68, in DeadlockWrap
  File "bsddb\__init__.pyc", line 270, in <lambda>
KeyError: 'winning'
Traceback (most recent call last):
  File "Base_s.py", line 3789, in sareport
  File "Base_s.py", line 4066, in __init__
  File "Base_s.py", line 4092, in __init__
  File "Base_s.py", line 4142, in filler
  File "shelve.pyc", line 121, in __getitem__
  File "bsddb\__init__.pyc", line 270, in __getitem__
  File "bsddb\dbutils.pyc", line 68, in DeadlockWrap
  File "bsddb\__init__.pyc", line 270, in <lambda>
KeyError: 'winning'
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 249, in win9
  File "Base_s.py", line 1767, in __init__
  File "Base_s.py", line 1776, in power_on
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 249, in win9
  File "Base_s.py", line 1767, in __init__
  File "Base_s.py", line 1776, in power_on
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 249, in win9
  File "Base_s.py", line 1767, in __init__
  File "Base_s.py", line 1776, in power_on
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 249, in win9
  File "Base_s.py", line 1767, in __init__
  File "Base_s.py", line 1776, in power_on
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 249, in win9
  File "Base_s.py", line 1767, in __init__
  File "Base_s.py", line 1776, in power_on
SystemError: unknown opcode
Traceback (most recent call last):
  File "Base_s.py", line 680, in searcher
  File "wx\_controls.pyc", line 4821, in Append
  File "wx\_controls.pyc", line 4713, in InsertStringItem
wx._core.PyAssertionError: C++ assertion "m_count == ListView_GetItemCount(GetHwnd())" failed at ..\..\src\msw\listctrl.cpp(1726) in wxListCtrl::InsertItem(): m_count should match ListView_GetItemCount
Traceback (most recent call last):
  File "Base_s.py", line 680, in searcher
  File "wx\_controls.pyc", line 4821, in Append
  File "wx\_controls.pyc", line 4713, in InsertStringItem
wx._core.PyAssertionError: C++ assertion "m_count == ListView_GetItemCount(GetHwnd())" failed at ..\..\src\msw\listctrl.cpp(1726) in wxListCtrl::InsertItem(): m_count should match ListView_GetItemCount
Traceback (most recent call last):
  File "Base_s.py", line 680, in searcher
  File "wx\_controls.pyc", line 4821, in Append
  File "wx\_controls.pyc", line 4713, in InsertStringItem
wx._core.PyAssertionError: C++ assertion "m_count == ListView_GetItemCount(GetHwnd())" failed at ..\..\src\msw\listctrl.cpp(1726) in wxListCtrl::InsertItem(): m_count should match ListView_GetItemCount
Traceback (most recent call last):
  File "Base_s.py", line 680, in searcher
  File "wx\_controls.pyc", line 4821, in Append
  File "wx\_controls.pyc", line 4713, in InsertStringItem
wx._core.PyAssertionError: C++ assertion "m_count == ListView_GetItemCount(GetHwnd())" failed at ..\..\src\msw\listctrl.cpp(1726) in wxListCtrl::InsertItem(): m_count should match ListView_GetItemCount
Traceback (most recent call last):
  File "Base_s.py", line 566, in add_item
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 566, in add_item
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "Base_s.py", line 680, in searcher
  File "wx\_controls.pyc", line 4821, in Append
  File "wx\_controls.pyc", line 4713, in InsertStringItem
wx._core.PyAssertionError: C++ assertion "m_count == ListView_GetItemCount(GetHwnd())" failed at ..\..\src\msw\listctrl.cpp(1726) in wxListCtrl::InsertItem(): m_count should match ListView_GetItemCount
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "Base_s.py", line 215, in ask_closer
  File "Base_s.py", line 4491, in __init__
  File "wx\_core.pyc", line 16712, in __getattr__
wx._core.PyDeadObjectError: The C++ part of the ask object has been deleted, attribute access no longer allowed.
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
Traceback (most recent call last):
  File "Base_s.py", line 247, in win8
  File "Base_s.py", line 4341, in __init__
  File "Base_s.py", line 4398, in gogogo
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 7: ordinal not in range(128)
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Users\Canela Santa\Canela Core\V1.4.5\Base.exe:2908: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
