Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
TypeError: starter() argument after * must be a sequence, not bool
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
TypeError: _sprint() argument after * must be a sequence, not bool


